version: '3.5'
services:
  app:
    image: toras9000/baget-mp:0.3.0-preview1
    build:
      context: ./build
      args:
        - BAGET_VER=v0.3.0-preview1
    restart: unless-stopped
    ports:
      - "8020:80"
    volumes:
      - ../volumes/baget/app/packages:/app/BaGet/packages
      - ../volumes/baget/app/symbols:/app/BaGet/symbols
      - ../volumes/baget/app/database:/app/database
      - ../volumes/baget/app/config:/app/config
    environment:
      - INIT_DB_TYPE=Sqlite
      - INIT_DB_CONN_STR=Data Source=/app/database/baget.db

